// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_string
// @generated from protobuf file "v1/echo/service.proto" (package "proto.v1.hello", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EchoService } from "./service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { EchoResponse } from "./service";
import type { EchoRequest } from "./service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service proto.v1.hello.EchoService
 */
export interface IEchoServiceClient {
    /**
     * @generated from protobuf rpc: Echo(proto.v1.hello.EchoRequest) returns (proto.v1.hello.EchoResponse);
     */
    echo(input: EchoRequest, options?: RpcOptions): UnaryCall<EchoRequest, EchoResponse>;
}
/**
 * @generated from protobuf service proto.v1.hello.EchoService
 */
export class EchoServiceClient implements IEchoServiceClient, ServiceInfo {
    typeName = EchoService.typeName;
    methods = EchoService.methods;
    options = EchoService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Echo(proto.v1.hello.EchoRequest) returns (proto.v1.hello.EchoResponse);
     */
    echo(input: EchoRequest, options?: RpcOptions): UnaryCall<EchoRequest, EchoResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<EchoRequest, EchoResponse>("unary", this._transport, method, opt, input);
    }
}
