[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_format = "%(asctime)s[%(name)-12s|%(lineno)-4s][%(levelname)1.4s] : %(message)s"
log_date_format = "%Y-%M-%D %H:%M:%S"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::SyntaxWarning"
]
testpaths = [
    "tests",
]
addopts = [
    "--config=../config.yml",  # your test config file
]

[tool.coverage.report]
skip_empty = true  # excloud empty file
