# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/echo/service.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'v1/echo/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15v1/echo/service.proto\x12\x0eproto.v1.hello\x1a\x1b\x62uf/validate/validate.proto\")\n\x0b\x45\x63hoRequest\x12\x1a\n\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"(\n\x0c\x45\x63hoResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2P\n\x0b\x45\x63hoService\x12\x41\n\x04\x45\x63ho\x12\x1b.proto.v1.hello.EchoRequest\x1a\x1c.proto.v1.hello.EchoResponseB|\n\x12\x63om.proto.v1.helloB\x0cServiceProtoP\x01\xa2\x02\x03PVH\xaa\x02\x0eProto.V1.Hello\xca\x02\x0eProto\\V1\\Hello\xe2\x02\x1aProto\\V1\\Hello\\GPBMetadata\xea\x02\x10Proto::V1::Hellob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.echo.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.proto.v1.helloB\014ServiceProtoP\001\242\002\003PVH\252\002\016Proto.V1.Hello\312\002\016Proto\\V1\\Hello\342\002\032Proto\\V1\\Hello\\GPBMetadata\352\002\020Proto::V1::Hello'
  _globals['_ECHOREQUEST'].fields_by_name['name']._loaded_options = None
  _globals['_ECHOREQUEST'].fields_by_name['name']._serialized_options = b'\272H\003\310\001\001'
  _globals['_ECHOREQUEST']._serialized_start=70
  _globals['_ECHOREQUEST']._serialized_end=111
  _globals['_ECHORESPONSE']._serialized_start=113
  _globals['_ECHORESPONSE']._serialized_end=153
  _globals['_ECHOSERVICE']._serialized_start=155
  _globals['_ECHOSERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
